//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAODICH
    {
        public int maGiaoDich { get; set; }
        public int maHoaDon { get; set; }
        public string soTKNganHang { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
