//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string maNhanVien { get; set; }
        public bool kiemDuyet { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
