//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIM()
        {
            this.XUATCHIEUx = new HashSet<XUATCHIEU>();
        }
    
        public string maPhim { get; set; }
        public string tenPhim { get; set; }
        public System.DateTime ngayPhatHanh { get; set; }
        public string moTa { get; set; }
        public string anhBia { get; set; }
        public string maTheLoai { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public Nullable<int> luotXem { get; set; }
    
        public virtual THELOAIPHIM THELOAIPHIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XUATCHIEU> XUATCHIEUx { get; set; }
    }
}
