//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAPPHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAPPHIM()
        {
            this.PHONGCHIEUx = new HashSet<PHONGCHIEU>();
        }
    
        public string maRap { get; set; }
        public string diaChi { get; set; }
        public string trangThai { get; set; }
        public Nullable<System.DateTime> gioMoCua { get; set; }
        public Nullable<System.DateTime> gioDongCua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGCHIEU> PHONGCHIEUx { get; set; }
    }
}
