//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int id { get; set; }
        public string tieuDe { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public string maNhanVien { get; set; }
        public string anhTieuDe { get; set; }
        public string anhNoiDung { get; set; }
        public Nullable<int> luotXem { get; set; }
        public Nullable<bool> daDuyet { get; set; }
        public Nullable<bool> trangThai { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
