//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public int maVe { get; set; }
        public string maGhe { get; set; }
        public string maXuatChieu { get; set; }
        public Nullable<int> maHoaDon { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual VITRIGHE VITRIGHE { get; set; }
        public virtual XUATCHIEU XUATCHIEU { get; set; }
    }
}
