//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XUATCHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XUATCHIEU()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public string maXuatChieu { get; set; }
        public string maPhim { get; set; }
        public string maPhong { get; set; }
        public Nullable<System.DateTime> ngayChieu { get; set; }
        public Nullable<System.TimeSpan> gioChieu { get; set; }
        public Nullable<double> giaXuatChieu { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        public virtual PHONGCHIEU PHONGCHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
    }
}
